#Application Configuration
#Mon Sep 22 12:46:28 CEST 2025
Array\ Border=\#15a9c8c8
High\ Priority\ Border=\#ff0020d8
Palette\ 0=\#dfff4373
Palette\ 1=\#64ffff00
Palette\ 2=\#64ff00d1
Palette\ 3=\#640000ff
Palette\ Text=\#ffffffff
Selected\ Tile=\#c800ff00
Selection\ Lasso=\#2f9ed433
lastImageDirectory=D\:\\Sync\\Documents\\Projets\\Megadrive\\Code\\Project-Faster\\res\\draft\\backgrounds
lastMaskDirectory=D\:\\Sync\\Documents\\Projets\\Megadrive\\Code\\Project-Faster\\res\\draft\\backgrounds
