name: CI

on:
  push:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: maven-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-${{ runner.arch }}-

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '8'
          cache: maven

      - name: Build with Maven
        run: |
          mvn -B -e -ntp clean package
